#KAM:RS:Matclable:a\T:m:nl:a\S:C:-nip:-cp
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx-replica
  namespace: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-replica-pod
      labels: 
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest 
        #image: nginx:1.14.2
        ports:
          - containerPort: 80

